### ISSUE TITLE
need help for 'gen_pts.py'

### ISSUE THREAD

**Issue by yangshunDragon** [DC1991/FS_Net#10]
I used files given as below:
  ['laptop_air_xin_norm.ply', 'laptop_mac_pro_norm.ply', 'laptop_alienware_norm.ply']
I ran pose_data.py successfully and got  *_label.pkl files. and then I ran gen_pts.py while I got some errors.

Traceback (most recent call last):
  File "gen_pts.py", line 152, in <module>
    render_pre(path)
  File "gen_pts.py", line 20, in render_pre
    renderer.add_object(obj, model)
  File "/home/robot/***/FS_Net/prepare_data/renderer_py.py", line 378, in add_object
    vertices = np.array(list(zip(model['pts'], model['normals'],
KeyError: 'normals'

Anybody have similiar problem? and How to solve?
BTW, what exactly gen_pts.py would generate for training?

**Comment by Lynne-Zheng-Linfang** [comment]
> I used files given as below: ['laptop_air_xin_norm.ply', 'laptop_mac_pro_norm.ply', 'laptop_alienware_norm.ply'] I ran pose_data.py successfully and got *_label.pkl files. and then I ran gen_pts.py while I got some errors.
> 
> Traceback (most recent call last): File "gen_pts.py", line 152, in render_pre(path) File "gen_pts.py", line 20, in render_pre renderer.add_object(obj, model) File "/home/robot/***/FS_Net/prepare_data/renderer_py.py", line 378, in add_object vertices = np.array(list(zip(model['pts'], model['normals'], KeyError: 'normals'
> 
> Anybody have similiar problem? and How to solve? BTW, what exactly gen_pts.py would generate for training?

Hi, I came to the same issue, but solved it by changing the Line13 of gen_pts.py from 
```python
renderer = create_renderer(640, 480, renderer_type='python')
```
to
```python
renderer = create_renderer(640, 480, renderer_type='python', shading='cate')
```

Hope this helps.

**Comment by HannahHaensen** [comment]
@yangshunDragon or @Lynne-Zheng-Linfang  did gen_pts work normally for you? I stumbled over this issue: https://github.com/DC1991/FS_Net/issues/15

and meet a similar problem could you explain gen_pts if it worked in the end for you?
